spring.application.name=JobPortalSystem


spring.datasource.password=password
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal_system
spring.datasource.username=linojoy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Format SQL Queries
spring.jpa.properties.hibernate.format_sql=true
